# Generated by Django 4.0.3 on 2022-04-06 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=60, null=True, validators=[django.core.validators.RegexValidator(message='Telefoonnummer moet in dit formaat zijn: 05999999999', regex='^(05)\\d{9}$')])),
                ('address', models.CharField(max_length=100)),
                ('pickup_date', models.DateTimeField()),
                ('total', models.IntegerField()),
                ('status', models.CharField(choices=[(1, 'Created'), (2, 'Paid'), (3, 'Cancelled'), (4, 'Bounced'), (5, 'Completed')], default=1, max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
