# Generated by Django 4.0.3 on 2022-04-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_variantmodel_variant'),
        ('orders', '0003_remove_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='orders.Order_Product', to='products.product'),
        ),
    ]
