# Generated by Django 4.0.5 on 2022-08-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_first_name_order_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[(1, 'Cash'), (2, 'Online')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
