# Generated by Django 4.0.3 on 2022-04-06 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_variantmodel_alter_product_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantmodel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
