# Generated by Django 4.0.5 on 2022-06-03 13:03

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_variant_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
    ]
