# Generated by Django 4.0.3 on 2022-04-04 14:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('candles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
