# Generated by Django 4.0.5 on 2022-06-03 12:45

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_variant_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=[('#FFFFFF', 'white'), ('#000000', 'black')]),
        ),
    ]
